apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: 
spec:
  template:
    metadata: #pod definition starts
      name: postgres
      labels:
        tier: db-tier
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value : mysecretpassword #pod definition ends
  replicas: 3
  selector: 
    matchLabels: 
      type: front-end