apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 3000 #port: 80 we changed the port as voting-app also runnign on localhost 
    targetPort: 80
  selector:
    name: result-app-pod
    app: demo-voting-app